Repository xerial/snappy-java, pull requests merged in 2023-09, with the labels that each got.

#508 feature: Upgrade the internal snappy version to 1.1.10 (1.1.8 was wrongly used before)
  .github/workflows/build-native.yml
  Makefile
  Makefile.common
  src/main/resources/org/xerial/snappy/native/Mac/aarch64/libsnappyjava.dylib
Labels: feature

#510 internal: Support JDK21
  .github/workflows/test.yml
  sbt
  src/test/java/org/xerial/snappy/pool/CachingBufferPoolTest.java
Labels: feature, internal

#515 Fix GLIBC_2.32 not found error in ppc64le on an oldedr version of Linux (e.g,. RedHat8.6) #512
  docker/dockcross-ppc64le
Labels: bug

#518 internal fix: Use Windows-aarch64 target name
  Makefile
  Makefile.common
  src/main/resources/org/xerial/snappy/native/Windows/aarch64/libsnappyjava.so
Labels: bug, internal

#520 win-aarch64 (fix): Fix dll name
  Makefile.common
  src/main/resources/org/xerial/snappy/native/Windows/aarch64/libsnappyjava.so
  src/main/resources/org/xerial/snappy/native/Windows/aarch64/snappyjava.dll
Labels: bug
