Repository xerial/snappy-java, pull requests merged in 2023-05, with the labels that each got.

#412 add workaround for resource management issue in URLClassloader
  src/main/java/org/xerial/snappy/SnappyLoader.java
Labels: feature

#436 Rebuild Linux Arm binaries with LTS version of cross-compiles using glibc 2.28
  docker/dockcross-aarch64
  docker/dockcross-arm64
  src/main/resources/org/xerial/snappy/native/Linux/aarch64/libsnappyjava.so
  src/main/resources/org/xerial/snappy/native/Windows/x86/snappyjava.dll
  src/main/resources/org/xerial/snappy/native/Windows/x86_64/snappyjava.dll
Labels: feature

#438 Release snapshot versions when native libs are updated
  .github/workflows/snapshot.yml
Labels: internal

#440 Feature: Use LTS cross-compiler for Linux armv6/armv7 to use glibc 2.28
  .gitignore
  Makefile
  Makefile.common
  docker/dockcross-armv6
  docker/dockcross-armv7
  src/main/resources/org/xerial/snappy/native/Linux/armv6/libsnappyjava.so
  src/main/resources/org/xerial/snappy/native/Linux/armv7/libsnappyjava.so
  src/main/resources/org/xerial/snappy/native/Windows/x86/snappyjava.dll
  src/main/resources/org/xerial/snappy/native/Windows/x86_64/snappyjava.dll
Labels: feature

#442 Feature: Android arm64 support
  Makefile
  Makefile.common
  docker/dockcross-android-arm64
  src/main/resources/org/xerial/snappy/native/Linux/android-aarch64/libsnappyjava.so
  src/main/resources/org/xerial/snappy/native/Windows/x86/snappyjava.dll
  src/main/resources/org/xerial/snappy/native/Windows/x86_64/snappyjava.dll
Labels: feature

#444 Trigger native lib build on PR
  .github/workflows/build-native.yml
  Makefile
  Makefile.common
Labels: internal

#446 internal: Run CI tests on native file change
  .github/workflows/test.yml
Labels: internal

#447 internal: Fix commit message
  .github/workflows/build-native.yml
Labels: bug, internal

#448 internal: Run CI tests for update-native-libs branch
  .github/workflows/build-native.yml
Labels: internal

#449 internal: Fix CI target branch
  .github/workflows/build-native.yml
  .github/workflows/test.yml
Labels: bug, internal

#451 intertnal: Fix CI watch target files
  .github/workflows/test.yml
Labels: internal
